### ISSUE TITLE
"statSync" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by EnSheep** [unjs/pkg-types#201] opened 2024-11-23 03:03 UTC
### Environment

pkg-types@1.2.1

### Reproduction

error during build:                                                                           10:59:10  
node_modules/.pnpm/pkg-types@1.2.1/node_modules/pkg-types/dist/index.mjs (1:9): "statSync" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/pkg-types@1.2.1/node_modules/pkg-types/dist/index.mjs".file: D:/wj/wj-duty-client/node_modules/.pnpm/pkg-types@1.2.1/node_modules/pkg-types/dist/index.mjs:1:9

1: import { statSync, promises } from 'node:fs';
            ^
2: import { resolve, join, isAbsolute, dirname } from 'pathe';
3: import { resolvePath } from 'mlly';

### Describe the bug

error during build:                                                                           10:59:10  
node_modules/.pnpm/pkg-types@1.2.1/node_modules/pkg-types/dist/index.mjs (1:9): "statSync" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/pkg-types@1.2.1/node_modules/pkg-types/dist/index.mjs".file: D:/wj/wj-duty-client/node_modules/.pnpm/pkg-types@1.2.1/node_modules/pkg-types/dist/index.mjs:1:9

1: import { statSync, promises } from 'node:fs';
            ^
2: import { resolve, join, isAbsolute, dirname } from 'pathe';
3: import { resolvePath } from 'mlly';

**Comment by pi0** [comment] 2024-11-26 16:04
Can you please share a reproduction? 🙏🏼

**Comment by pi0** [comment] 2024-12-27 11:27
closing as no reproduction provided. however issue is likely using this package within browser env which is unsupported.

**Closed by pi0** 2024-12-27 11:27 UTC
Labels: needs-reproduction

**Comment by hey-david-perez** [comment] 2025-01-16 18:34
Having the same problem. Not being able to reproduce it. I've seen is triggered by Unocss on my case.

```
unocss 65.4.2
└─┬ @unocss/preset-icons 65.4.2
  └─┬ @iconify/utils 2.2.1
    ├─┬ local-pkg 0.5.1
    │ ├─┬ mlly 1.7.4
    │ │ └── pkg-types 1.3.1
    │ └── pkg-types 1.3.1
    └─┬ mlly 1.7.4
      └── pkg-types 1.3.1
```

**Comment by pi0** [comment] 2025-01-16 18:45
It is likely a dependency that uses `import {}` instead of `import type {}` causing vite to try to load runtime code. not an issue with pkg-types.

**Comment by sunpm** [comment] 2025-01-21 10:09
> Having the same problem. Not being able to reproduce it. I've seen is triggered by Unocss in my case.
> 
> ```
> unocss 65.4.2
> └─┬ @unocss/preset-icons 65.4.2
>   └─┬ @iconify/utils 2.2.1
>     ├─┬ local-pkg 0.5.1
>     │ ├─┬ mlly 1.7.4
>     │ │ └── pkg-types 1.3.1
>     │ └── pkg-types 1.3.1
>     └─┬ mlly 1.7.4
>       └── pkg-types 1.3.1
> ```

me too

**Comment by pi0** [comment] 2025-01-21 10:33
It is not an issue with pkg-types but at least please consider sharing a minimal reproduction so we can find where to fix it from.

**Comment by sunpm** [comment] 2025-01-22 01:41
> It is not an issue with pkg-types but at least please consider sharing a minimal reproduction so we can find where to fix it from.

I'm sorry, the error was caused by using the export method of unocss in js, which was resolved after removal.
```js
import { isString } from 'unocss'
```
