### ISSUE TITLE
Test case would not pass

### ISSUE THREAD

**Issue by werheng** [unjs/pkg-types#180] opened 2024-05-09 06:56 UTC
### Environment

MacOS
pnpm@9.0.4
yarn@1.22.22

### Reproduction

Install global dependencies.
```bash
pnpm add yarn -g
yarn add pkg-types -g
```

### Describe the bug

When I use yarn add some global dependencies.It will create `package.json` and `yarn.lock` in `/Users/xxx`.

![image](https://github.com/unjs/pkg-types/assets/36580301/9e4f5604-6671-47d8-ac92-be86149e9dc5)

**Comment by pi0** [comment] 2024-05-09 17:53
Hey. Do you still have same issue? You should use `corepack enable` > `pnpm install` > `pnpm run test` as this repository is maintained and tested using pnpm. 

(closing as your nice PR was merged and I cannot reproduce but please just mention if still have issue for running tests locally)

**Closed by pi0** 2024-05-09 17:53 UTC
